### ISSUE TITLE
Mute/Unmute the microphone by single clicking on the tray icon

### ISSUE THREAD

**Issue by im1x** [iXab3r/MicSwitch#37]
I think it would be convenient if when you click on the program icon in the tray, the microphone mute or unmute.

Thanks for the program, it helps a lot👍

**Comment by iXab3r** [comment]
Added it in v185, please not that there will be delay before mute/unmute on a single click, this delay depends on double-click delay that is configured in Windows. 
Tbh it feels a bit laggy due to the fact that program has to wait a bit to distinguish double and single click on tray icon. 
Please reopen if you feel that it will be better to add some option to remove that effect, e.g. remove delay by disabling double-click (hide/show app)
